"use client";
import { useState } from "react";
import Link from "next/link";

type Row = Record<string, string>;
export function TrustAssistant() {
  const [question, setQuestion] = useState(""); const [answer, setAnswer] = useState(""); const [busy, setBusy] = useState(false);
  async function ask(event: React.FormEvent) { event.preventDefault(); setBusy(true); setAnswer(""); try { const r = await fetch("/api/backend/operations/assistant", {method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({question})}); const data = await r.json(); setAnswer(data.answer ?? data.detail ?? "Assistant unavailable"); } finally { setBusy(false); } }
  return <section className="feature-workspace"><div className="eyebrow">LOCAL WORKSPACE ASSISTANT</div><h1>Trust assistant</h1><p>Get a quick summary from your organization’s shipment, risk and finance records. No external AI service is used.</p><form className="feature-form" onSubmit={ask}><label>Ask about this workspace<input required value={question} onChange={e=>setQuestion(e.target.value)} placeholder="How many shipments are in progress?"/></label><button className="button" disabled={busy}>{busy?"Checking…":"Ask assistant"}</button></form>{answer&&<p className="feature-message feature-success" role="status">{answer}</p>}</section>;
}
export function ProofLedger({ records, initialProofs }: {records: Record<string, unknown>[]; initialProofs: Row[]}) {
  const [proofs,setProofs]=useState(initialProofs); const [message,setMessage]=useState(""); const [busy,setBusy]=useState("");
  async function anchor(row:Record<string,unknown>) { const kind=String(row.record_type); setBusy(String(row.id)); setMessage(""); try { const r=await fetch(`/api/backend/operations/proofs/${kind}/${row.id}`,{method:"POST"}); const result=await r.json(); if(!r.ok)throw new Error(result.detail); const list=await fetch("/api/backend/operations/proofs"); setProofs(await list.json()); setMessage(`Proof created: ${result.digest}`); } catch(e) {setMessage(e instanceof Error?e.message:"Could not create proof");} finally{setBusy("");} }
  return <section className="feature-workspace"><div className="eyebrow">TAMPER EVIDENCE</div><h1>Proof ledger</h1><p>Record SHA-256 proofs in a tenant-scoped linked ledger. This is a local verification alternative, not a public blockchain transaction.</p>{message&&<p className="feature-message feature-success" role="status">{message}</p>}<h2>Operational records</h2><div className="feature-table-wrap"><table className="feature-table"><thead><tr><th>Record</th><th>Module</th><th>Status</th><th>Action</th></tr></thead><tbody>{records.map(row=><tr key={String(row.id)}><td>{String(row.name)}</td><td>{String(row.record_type)}</td><td>{String(row.status)}</td><td><button disabled={busy===String(row.id)} onClick={()=>anchor(row)}>{busy===String(row.id)?"Creating…":"Create proof"}</button></td></tr>)}</tbody></table></div><h2>Recent proofs</h2><div className="feature-table-wrap"><table className="feature-table"><thead><tr><th>Type</th><th>Record ID</th><th>SHA-256 digest</th><th>Verify</th></tr></thead><tbody>{proofs.map(proof=><tr key={proof.id}><td>{proof.subject_type}</td><td>{proof.subject_id}</td><td><code>{proof.digest}</code></td><td><Link href={`/verify/${proof.digest}`}>Open verification link</Link></td></tr>)}{!proofs.length&&<tr><td colSpan={4}>No proofs yet.</td></tr>}</tbody></table></div></section>;
}
